### ISSUE TITLE
System.Private.CoreLib: Exception while executing function: Functions.test. System.Private.CoreLib: Result: Failure Exception: Cannot locate the method signature with the given input

### ISSUE THREAD

**Issue by ZYJ-SH-CN** [Azure/azure-functions-java-worker#123]
I am trying the blobtrigger in java. Just add the-function as default, set up my configuration.
Got following error. But I have no clue why it does not work.

`018-06-13T15:10:13.681 [Error] System.Private.CoreLib: Exception while executing function: Functions.Ctblobtriggertest. System.Private.CoreLib: Result: Failure
Exception: Cannot locate the method signature with the given input
Stack: java.lang.NoSuchMethodException: Cannot locate the method signature with the given input

	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.lambda$execute$0(JavaMethodExecutor.java:49)

	at java.util.Optional.orElseThrow(Optional.java:290)

	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:49)

	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:47)

	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)

	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)

	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)

	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:91)

	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)

	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)

	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)

	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)

	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

.
`

**Comment by pragnagopa** [comment]
We have a breaking change as part of the latest functions release. Please see: https://github.com/Azure/app-service-announcements/issues/112 and https://github.com/Azure/app-service-announcements-discussions/issues/50

**Comment by ZYJ-SH-CN** [comment]
great! After long time debugging, now it works!

**Comment by RishabhTayal** [comment]
@ZYJ-SH-CN What was the fix? @pragnagopa?

**Comment by MarcoCapussoAvnet** [comment]
@pragnagopa What was the fix????????????????????????

**Comment by pragnagopa** [comment]
This is a closed issue. Please open new issue with repro steps
