### ISSUE TITLE
I get java.lang.NoSuchMethodException when running TimerTrigger

### ISSUE THREAD

**Issue by peterivarsson** [Azure/azure-functions-java-worker#128]
Its seems to trig the function OK.
But after that I get an NoSuchMethodException
It seem to load "com.cybercom.bam.photo.azure.Function.photo" OK.
But tries to run Functions.photo

System.Private.CoreLib: Exception while executing function: Functions.photo. 
(Functions.photo not as Expected Function.photo)
Exception: Cannot locate the method signature with the given input

````
package com.cybercom.bam.photo.azure;

import com.microsoft.azure.serverless.functions.annotation.*;
import com.microsoft.azure.serverless.functions.ExecutionContext;

/**
 * Azure Functions with Timer Trigger.
 */
public class Function {

    @FunctionName("photo")
    public void photo(
            @TimerTrigger(name = "phototimer", schedule = "0 */2 * * * *") String timerInfo,
            final ExecutionContext context) {
        
    }
}
````
````
2018-06-14T06:08:47.181 [Information] Worker initialized
2018-06-14T06:08:50.258 [Information] "photo" loaded (ID: 494e7c8a-7f81-4f67-b1d9-a332b0935c81, Reflection: "D:\home\site\wwwroot\bam-photos-1.0.1-SNAPSHOT.jar"::"com.cybercom.bam.photo.azure.Function.photo")
2018-06-14T06:08:50.258 [Information] "photo" loaded (ID: 494e7c8a-7f81-4f67-b1d9-a332b0935c81, Reflection: "D:\home\site\wwwroot\bam-photos-1.0.1-SNAPSHOT.jar"::"com.cybercom.bam.photo.azure.Function.photo")
2018-06-14T06:10:00.142 [Information] Executing 'Functions.photo' (Reason='Timer fired at 2018-06-14T06:10:00.0263816+00:00', Id=256a5904-bd3b-4b27-a3ed-e38705510785)
2018-06-14T06:10:00.142 [Information] Executing 'Functions.photo' (Reason='Timer fired at 2018-06-14T06:10:00.0263816+00:00', Id=256a5904-bd3b-4b27-a3ed-e38705510785)
2018-06-14T06:10:01.249 [Warning] Cannot locate the method signature with the given input
2018-06-14T06:10:01.320 [Warning] Cannot locate the method signature with the given input
2018-06-14T06:10:01.512 [Error] System.Private.CoreLib: Exception while executing function: Functions.photo. System.Private.CoreLib: Result: Failure
Exception: Cannot locate the method signature with the given input
Stack: java.lang.NoSuchMethodException: Cannot locate the method signature with the given input
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.lambda$execute$0(JavaMethodExecutor.java:49)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:49)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:47)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:91)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
.
2018-06-14T06:10:01.620 [Error] Executed 'Functions.photo' (Failed, Id=256a5904-bd3b-4b27-a3ed-e38705510785)
2018-06-14T06:10:01.560 [Error] System.Private.CoreLib: Exception while executing function: Functions.photo. System.Private.CoreLib: Result: Failure
Exception: Cannot locate the method signature with the given input
Stack: java.lang.NoSuchMethodException: Cannot locate the method signature with the given input
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.lambda$execute$0(JavaMethodExecutor.java:49)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:49)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:47)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:91)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
.
2018-06-14T06:10:01.661 [Error] Executed 'Functions.photo' (Failed, Id=256a5904-bd3b-4b27-a3ed-e38705510785)
2018-06-14T06:10:01.715 [Debug] Function 'Host.Functions.photo' updated status: Last='2018-06-14T06:10:00.0067234+00:00', Next='2018-06-14T06:12:00.0000000+00:00', LastUpdated='2018-06-14T06:10:00.0067234+00:00'
````
In pom.xml
````
<!-- Azure dependencies -->
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-functions-java-core</artifactId>
            <version>1.0.0-beta-3</version>
        </dependency>
````
What am I doing wrong?

**Comment by pragnagopa** [comment]
This is expected. Here is the the breaking change annoucement https://github.com/Azure/app-service-announcements/issues/112 Please update function code and redeploy
Please subscribe to the the repo https://github.com/Azure/app-service-announcements to receive notifications on future regarding functions runtime updates.

**Comment by asavaritayal** [comment]
Closing the issue due to inactivity. Please feel free to re-open if you're still facing the same error.
