### ISSUE TITLE
TimerTrigger functions started failing since last 2 days

### ISSUE THREAD

**Issue by ganeshchippada** [Azure/azure-functions-java-worker#129]
We are having a function app running for past 30 days. Suddenly the time triggers started failing and throwing exceptions. 

**Stacktrace:**

System.Private.CoreLib: Exception while executing function: Functions.verifySubscriptions. System.Private.CoreLib: Result: Failure
Exception: Cannot locate the method signature with the given input
Stack: java.lang.NoSuchMethodException: Cannot locate the method signature with the given input
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.lambda$execute$0(JavaMethodExecutor.java:49)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:49)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:47)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:91)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
.

**Comment by pragnagopa** [comment]
This is expected. Please see: https://github.com/Azure/app-service-announcements/issues/112

**Comment by ganeshchippada** [comment]
@pragnagopa  thanks . that was helpful.

**Comment by asavaritayal** [comment]
Closing issue since this seems to be resolved.
