### ISSUE TITLE
Running Functions locally does not work on Java 10

### ISSUE THREAD

**Issue by DennisVis** [Azure/azure-functions-java-worker#152]
Running Functions locally does not work on Java 10 (and other 9+ versions most likely).
The worker produces a runtime exception when executing `com.microsoft.azure.functions.worker.reflect.DefaultClassLoaderProvider#addUrlToSystemClassLoader()`. This is due to the fact that an assumption is made there that the `ClassLoader` returned by `ClassLoader.getSystemClassLoader()` is of type `URLClassLoader` and is cast as such. That assumption is not true for Java 9 and up.

#### Repro steps

Run `mvn clean package azure-functions:run` while using the Java 10 compiler.

#### Expected behavior

The Functions run and are executable locally.

#### Actual behavior

The Functions produce an error upon execution:

<pre><code>
[08/06/2018 11:46:28] Exception: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
[08/06/2018 11:46:28] Stack: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
[08/06/2018 11:46:28] 	at com.microsoft.azure.functions.worker.reflect.DefaultClassLoaderProvider.addUrlToSystemClassLoader(DefaultClassLoaderProvider.java:75)
[08/06/2018 11:46:28] 	at com.microsoft.azure.functions.worker.reflect.DefaultClassLoaderProvider.addUrl(DefaultClassLoaderProvider.java:65)
[08/06/2018 11:46:28] 	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.addSearchPathsToClassLoader(JavaFunctionBroker.java:58)
[08/06/2018 11:46:28] 	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.loadMethod(JavaFunctionBroker.java:30)
[08/06/2018 11:46:28] 	at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:27)
[08/06/2018 11:46:28] 	at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:9)
[08/06/2018 11:46:28] 	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[08/06/2018 11:46:28] 	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:91)
[08/06/2018 11:46:28] 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[08/06/2018 11:46:28] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[08/06/2018 11:46:28] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
[08/06/2018 11:46:28] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
</code></pre>

**Comment by asavaritayal** [comment]
Thanks for filing the issue. Currently, we don't support Java 9 or 10. Since both of these are not LTS versions, we don't have any plans to support them either.

**Comment by haonm-fpt** [comment]
i have issues same as this . but i using java 8 :( 
![image](https://user-images.githubusercontent.com/58904112/70861083-2798d080-1f5c-11ea-92ce-3d3bcfb8499f.png)

**Comment by maxstreifeneder** [comment]
any solution to this? same issue here with java 8.

**Comment by mnriem** [comment]
If you are seeing this I would recommend using the same version as used by the runtime when it is deployed to Azure. Just our of curiosity what specific version / vendor are you using locally?

**Comment by maxstreifeneder** [comment]
the generated file sets JDK Version 8, which I'm also using via JAVA_HOME: 

java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

@haonm-fpt (+4 additional folks hitting the thumbs up button) had stated the same problem. Would propose the reopen this issue. There's no combination of Java version which would make that work for me.

**Comment by mnriem** [comment]
@maxstreifeneder I suggest you open a separate issue for the JDK 8 issue as it seems this one was closed months before @haonm-fpt commented
