### ISSUE TITLE
Error: Host crashes on empty body when string is the input parameter

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-java-worker#19]
When making an HTTP request to a Java HTTP Triggered Function, it throws a 500 error. If you give it a body with a single piece of whitespace.

### Repro:

Make a `GET` request to this following function ("http://localhost:7071")

```java
package com.chris.functions;

import com.microsoft.azure.serverless.functions.annotation.*;
import com.microsoft.azure.serverless.functions.ExecutionContext;

/**
 * Hello function with HTTP Trigger.
 */
public class Function {
    @FunctionName("hello")
    public String hello(@HttpTrigger(name = "req", methods = {"get", "post"}, authLevel = AuthorizationLevel.ANONYMOUS) String req,
                        ExecutionContext context) {
        return String.format("Hello, %s!", req);
    }
}
```

#### Error:
```
[10/19/2017 9:42:50 PM] Exception while executing function: Functions.hello
[10/19/2017 9:42:50 PM] Exception while executing function: Functions.hello. System.Private.CoreLib: Result: Cannot locate the method signature with the given input
Exception: Cannot locate the method signature with the given input
Stack: java.lang.NoSuchMethodException: Cannot locate the method signature with the given input
[10/19/2017 9:42:50 PM]         at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.lambda$execute$0(JavaMethodExecutor.java:33)
[10/19/2017 9:42:50 PM]         at java.util.Optional.orElseThrow(Optional.java:290)
[10/19/2017 9:42:50 PM]         at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:33)
[10/19/2017 9:42:50 PM]         at com.microsoft.azure.webjobs.script.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:40)
[10/19/2017 9:42:50 PM]         at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[10/19/2017 9:42:50 PM]         at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[10/19/2017 9:42:50 PM]         at com.microsoft.azure.webjobs.script.handler.MessageHandler.handle(MessageHandler.java:41)
[10/19/2017 9:42:50 PM]         at com.microsoft.azure.webjobs.script.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:84)
[10/19/2017 9:42:50 PM]         at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
[10/19/2017 9:42:50 PM]         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[10/19/2017 9:42:50 PM]         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[10/19/2017 9:42:50 PM]         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[10/19/2017 9:42:50 PM]         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[10/19/2017 9:42:50 PM] .
[10/19/2017 9:42:51 PM] Function completed (Failure, Id=3fd20974-19c1-4c7b-b475-d034277839be, Duration=75ms)
[10/19/2017 9:42:51 PM]
[10/19/2017 9:42:51 PM] Executed 'Functions.hello' (Failed, Id=3fd20974-19c1-4c7b-b475-d034277839be)
[10/19/2017 9:42:51 PM] System.Private.CoreLib: Exception while executing function: Functions.hello. System.Private.CoreLib: Result: Cannot locate the method signature with the given input
Exception: Cannot locate the method signature with the given input
Stack: java.lang.NoSuchMethodException: Cannot locate the method signature with the given input
[10/19/2017 9:42:51 PM]         at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.lambda$execute$0(JavaMethodExecutor.java:33)
[10/19/2017 9:42:51 PM]         at java.util.Optional.orElseThrow(Optional.java:290)
[10/19/2017 9:42:51 PM]         at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:33)
[10/19/2017 9:42:51 PM]         at com.microsoft.azure.webjobs.script.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:40)
[10/19/2017 9:42:51 PM]         at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[10/19/2017 9:42:51 PM]         at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[10/19/2017 9:42:51 PM]         at com.microsoft.azure.webjobs.script.handler.MessageHandler.handle(MessageHandler.java:41)
[10/19/2017 9:42:51 PM]         at com.microsoft.azure.webjobs.script.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:84)
[10/19/2017 9:42:51 PM]         at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
[10/19/2017 9:42:51 PM]         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[10/19/2017 9:42:51 PM]         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[10/19/2017 9:42:51 PM]         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[10/19/2017 9:42:51 PM]         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[10/19/2017 9:42:51 PM] .
[10/19/2017 9:42:51 PM]   Function had errors. See Azure WebJobs SDK dashboard for details. Instance ID is '3fd20974-19c1-4c7b-b475-d034277839be'
[10/19/2017 9:42:51 PM] System.Private.CoreLib: Exception while executing function: Functions.hello. System.Private.CoreLib: Result: Cannot locate the method signature with the given input
Exception: Cannot locate the method signature with the given input
Stack: java.lang.NoSuchMethodException: Cannot locate the method signature with the given input
[10/19/2017 9:42:51 PM]         at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.lambda$execute$0(JavaMethodExecutor.java:33)
[10/19/2017 9:42:51 PM]         at java.util.Optional.orElseThrow(Optional.java:290)
[10/19/2017 9:42:51 PM]         at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:33)
[10/19/2017 9:42:51 PM]         at com.microsoft.azure.webjobs.script.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:40)
[10/19/2017 9:42:51 PM]         at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[10/19/2017 9:42:51 PM]         at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[10/19/2017 9:42:51 PM]         at com.microsoft.azure.webjobs.script.handler.MessageHandler.handle(MessageHandler.java:41)
[10/19/2017 9:42:51 PM]         at com.microsoft.azure.webjobs.script.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:84)
[10/19/2017 9:42:51 PM]         at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
[10/19/2017 9:42:51 PM]         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[10/19/2017 9:42:51 PM]         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[10/19/2017 9:42:51 PM]         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[10/19/2017 9:42:51 PM]         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Expected:

I expect a more helpful error message or potentially supporting an null body.

I also suggest we change the sample to not support GET or use the full HTTP object.

**Comment by JunyiYi** [comment]
Nullable types (including Optional<T>) have just been added to the runtime. But it will not work until the next deployment (~3 weeks) to Azure. For now you can use the following code as a workaround:
```java
public static String handler(HttpRequestMessage req) {
  req.getBody();
}
```

**Comment by christopheranderson** [comment]
Should we change the default Sample to use the HttpRequestMessage object? I think it might be more useful for folks doing `GET` methods.

**Comment by christopheranderson** [comment]
Also, the error message could maybe be more helpful? I thought it was not able to find my Function. I didn't read that message and think my input types were wrong.

**Comment by JunyiYi** [comment]
Sure. Both the samples and the logging messages are under refactoring.

**Comment by JunyiYi** [comment]
Fixed with BETA-2. Please update both Azure CLI runtime as well as Azure Functions Java core package version.
