### ISSUE TITLE
byte[] input broken

### ISSUE THREAD

**Issue by mjiderhamn** [Azure/azure-functions-java-worker#239]
It appears using `byte[]` as Function input has been broken. Functions that previously executed properly, and still execute properly in local dev environment, now results in exception when run in Azure.

#### Investigative information

Please provide the following:

- Timestamp: 2018-11-14 06:31:30.130 / 2018-11-14 06:32:12.900
- Function App name: 50shadesofserverless
- Function name(s) (as appropriate): transform / transformBlob (/transformStorageQueue)
- Invocation ID: 9bc21c42-c7d0-4385-afc7-e7e4a5ea73fe / 89b5e2bc-006f-4397-a61f-eeabab9878ad
- Region: EU North

#### Repro steps
```java
  // Also tried Optional<byte[]> and HttpRequestMessage<Optional<byte[]>>
  @FunctionName("transform")
  public byte[] transform(
      @HttpTrigger(name = "req", methods = {POST}, authLevel = AuthorizationLevel.ANONYMOUS, dataType = "binary") byte[] request,
      final ExecutionContext context) {
    ...
  }

  @FunctionName("transformStorageQueue")
  @QueueOutput(name = "queueResult", queueName = "out", connection = "AzureWebJobsStorage")
  public byte[] transformQueue(
      @QueueTrigger(name = "input", dataType = "binary", queueName = "in", connection = "AzureWebJobsStorage") byte[] input,
      final ExecutionContext context) {
    ...
  }

  @FunctionName("transformBlob")
  @BlobOutput(name = "blobResult", path = "out/{name}", connection = "AzureWebJobsStorage")
  public byte[] transformBlob(
      @BlobTrigger(name = "content", dataType = "binary", path = "in/{name}", connection = "AzureWebJobsStorage") byte[] content,
      final ExecutionContext context) {
    ...
  }
```

#### Expected behavior

Functions triggered and executed.

#### Actual behavior

HTTP results in this exception:
```
Result: Failure
Exception: ClassCastException: com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource cannot be cast to java.lang.String
Stack: java.lang.ClassCastException: com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource cannot be cast to java.lang.String
	at com.microsoft.azure.functions.worker.binding.DataOperations.apply(DataOperations.java:91)
	at com.microsoft.azure.functions.worker.binding.DataSource.computeByType(DataSource.java:56)
	at com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource.computeByType(RpcHttpRequestDataSource.java:20)
	at com.microsoft.azure.functions.worker.binding.DataSource.computeByName(DataSource.java:42)
	at com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource.computeByName(RpcHttpRequestDataSource.java:20)
	at com.microsoft.azure.functions.worker.binding.BindingDataStore.getDataByName(BindingDataStore.java:50)
	at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:59)
	at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:42)
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:52)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:51)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
...
```

Storage (blob and queue) result in:
```
Result: Failure
Exception: ClassCastException: [B cannot be cast to java.lang.String
Stack: java.lang.ClassCastException: [B cannot be cast to java.lang.String
	at com.microsoft.azure.functions.worker.binding.DataOperations.apply(DataOperations.java:91)
	at com.microsoft.azure.functions.worker.binding.DataSource.computeByType(DataSource.java:56)
	at com.microsoft.azure.functions.worker.binding.DataSource.computeByName(DataSource.java:42)
	at com.microsoft.azure.functions.worker.binding.BindingDataStore.getDataByName(BindingDataStore.java:50)
	at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:59)
	at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:42)
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:52)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:51)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
...
```

**Comment by pragnagopa** [comment]
Thank you reporting. This is a regression. As a workaround, please use `java.lang.Byte[]` instead of `byte[]`
Looking into this and will address it ASAP.

**Comment by mjiderhamn** [comment]
Updating `azure-functions-core-tools` locally so that `azure-functions-java-worker` bumps from [1.1.1-beta03](https://github.com/Azure/azure-functions-java-worker/releases/tag/v1.1.1-beta03) to [1.2.0-beta01-SNAPSHOT](https://github.com/Azure/azure-functions-java-worker/releases/tag/1.2.0-beta01-SNAPSHOT) makes it break locally too. So the breaking change is likely in between there.

**Comment by mjiderhamn** [comment]
@pragnagopa , workaround is a success for `@BlobTrigger` and `@QueueTrigger`.

`@HttpTrigger` however still giving the same error.

**Comment by pragnagopa** [comment]
@mjiderhamn - Verified PR fixes issue for HttpTrigger as well. Also, added unit tests.

**Comment by tharangahewa** [comment]
In which version has the issue with the HttpTrigger been fixed? I am not very clear about the version. I cloned the repo and ran my function app on  Azure Functions Java Worker  version [ 1.2.3]. Issue with HttpTrigger still persists.

**Comment by panneerpst** [comment]
Hello Team,
i am trying to run the azure sample functions code with the latest code from master branch + latest azure tools. But still i am getting the below error. Could you please let me know in which branch fix is available

[16-03-2019 05:46:51] Executed 'Functions.uppercase' (Failed, Id=60eab286-93de-4e29-8771-5c99afe8a874)
[16-03-2019 05:46:51] System.Private.CoreLib: Exception while executing function: Functions.uppercase. System.Private.CoreLib: Result: Failure
Exception: Cannot locate the method signature with the given input
Stack: java.lang.NoSuchMethodException: Cannot locate the method signature with the given input
[16-03-2019 05:46:51]   at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.lambda$execute$0(JavaMethodExecutor.java:49)
[16-03-2019 05:46:51]   at java.util.Optional.orElseThrow(Optional.java:290)
[16-03-2019 05:46:51]   at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:49)
[16-03-2019 05:46:51]   at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:47)
[16-03-2019 05:46:51]   at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[16-03-2019 05:46:51]   at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[16-03-2019 05:46:51]   at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[16-03-2019 05:46:51]   at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:91)
[16-03-2019 05:46:51]   at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
[16-03-2019 05:46:51]   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[16-03-2019 05:46:51]   at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[16-03-2019 05:46:51]   at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[16-03-2019 05:46:51]   at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[16-03-2019 05:46:51] .
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLL9Q97Q9REG", Request id "0HLL9Q97Q9REG:00000001": An unhandled exception was thrown by the application.
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.uppercase ---> Microsoft.Azure.WebJobs.Script.Rpc.RpcException: Result: Failure
Exception: Cannot locate the method signature with the given input
Stack: java.lang.NoSuchMethodException: Cannot locate the method signature with the given input
        at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.lambda$execute$0(JavaMethodExecutor.java:49)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:49)
        at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:47)
        at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
        at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
        at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
        at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:91)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by pragnagopa** [comment]
@panneerpst / @tharangahewa - this issue is closed. Please open a separate issue with repro code - including the function signature.

**Comment by josh-roberts-phision** [comment]
I believe I'm seeing this error as well on EventHubTrigger.  I am having trouble executing this trigger locally, but when deployed on App Function (Runtime version 2.0.12382.0 (beta) ) i get this error.

**Comment by pragnagopa** [comment]
@josh-roberts-phision - This issue is closed. Please open a new issue with repro including function signature
