### ISSUE TITLE
ClassCastException from Queue Trigger

### ISSUE THREAD

**Issue by raytucson** [Azure/azure-functions-java-worker#250]
See similar issue 239.  
Functions triggered from queues have stopped working due toClassCastException on ExecutionContextDataSource

#### Investigative information

Please provide the following:

- Timestamp: 2018-11-30T20:19:44.004
- Function App name: CongressDatabaseFunctions
- Function name(s) (as appropriate):  Insert
- Invocation ID: 36b350b2-7da8-44a2-9575-cecf98097ff0
- Region: arizona

#### Repro steps

Provide the steps required to reproduce the problem:

Using the Azure portal, manually add a message to the queue to invoke the trigger and subsequent function.

#### Expected behavior
The Function is called.

#### Actual behavior
ClassCastException

2018-11-30T20:19:44.130 [Information] Executing 'Functions.Filter' (Reason='New queue message detected on 'q000000000987654'.', Id=618ae505-b916-4144-9bf1-8bb514208d13)
2018-11-30T20:19:44.329 [Error] Executed 'Functions.Filter' (Failed, Id=618ae505-b916-4144-9bf1-8bb514208d13)

Result: Failure
Exception: ClassCastException: com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource cannot be cast to java.lang.String
Stack: java.lang.ClassCastException: com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource cannot be cast to java.lang.String
	at com.microsoft.azure.functions.worker.binding.DataOperations.apply(DataOperations.java:91)
	at com.microsoft.azure.functions.worker.binding.DataSource.computeByType(DataSource.java:56)

**Comment by pragnagopa** [comment]
@raytucson - Can you please share your function method signature?

**Comment by pragnagopa** [comment]
@raytucson - I am unable to repro this issue with queuetrigger.
@hoangelos  - Please open a separate issue. The issue you are seeing could be specific to Scala

**Comment by pragnagopa** [comment]
closing due to inactivity.
