### ISSUE TITLE
ServiceBusTrigger throws NullPointerException at BindingDataStore.getDataByName

### ISSUE THREAD

**Issue by MartijnTheunissen** [Azure/azure-functions-java-worker#289]
Hi,

I am writing a java function that consumes messages from a Service Bus queue.
The function however immediately throws the following an error message (see below).

#### Investigative information
- Timestamp:  2019-04-24 21:16:08.175
- Invocation ID: 8c73060c-3001-478c-bad4-76493c4e8cfa
- Region: Central US

#### Repro steps

1: Write a function with a ServiceBusTrigger like the one in the
[documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#trigger---java-example )

2: Send a message sent to a service bus queue:
<details>
<summary>message sent</summary>

```java
            int i = (int) (Math.random() * 10000);
            final String messageId = Integer.toString(i);
            Message message = new Message("test");
            message.setLabel("test");
            message.setMessageId(messageId);
            message.setTimeToLive(Duration.ofMinutes(2));
```
</details>

#### Expected behavior
After the message is invoked, it has run successfully with a message logged

#### Actual behavior

The following error is thrown:

Result: Failure
Exception: NullPointerException: 
Stack: 
<details>
<summary>stacktrace</summary>

```java
java.lang.NullPointerException
	at com.microsoft.azure.functions.worker.binding.BindingDataStore.getDataByName(BindingDataStore.java:50)
	at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:59)
	at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:42)
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:52)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:51)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
</details>

Thanks in advance!

**Comment by pragnagopa** [comment]
can you please share function singnature and also the generated function.json from target folder?
