### ISSUE TITLE
ExecutionContextDataSource cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by Ajay-Negi** [Azure/azure-functions-java-worker#315]
#### Problem Description
I have created a Azure Function app with a "saveUser" azure function of type POST. It was working fine earlier but now when I hit it, I get 500 Internal Server Error. 
I face the same issue with other PUT or POST request where I am sending details in json string DTO. GET methods are working fine though.

#### Investigative information

- Timestamp:  2019-07-25T06:34:59.353
- Invocation ID:  6a89684c-99aa-4618-8962-bb00305fc7f8
- Region:  East US

#### Repro steps
Here is the method signature that I am using. The userDTO is the json string in which I pass on the user details to be saved by this method.
```
@FunctionName("SaveUser")
public HttpResponseMessage saveUser(@HttpTrigger(name = "req", methods = {
    HttpMethod.POST }, route = "v1/users", authLevel = AuthorizationLevel.ANONYMOUS) 
    HttpRequestMessage<Optional<String>> request, String userDTO, final ExecutionContext context) 
     {
       <method logic goes here>
     }
```
#### Exception that I get in the logs:

```
Exception: ClassCastException: com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource cannot be cast to java.lang.String
Stack: java.lang.ClassCastException: com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource cannot be cast to java.lang.String
	at com.microsoft.azure.functions.worker.binding.DataOperations.apply(DataOperations.java:99)
	at com.microsoft.azure.functions.worker.binding.DataSource.computeByType(DataSource.java:56)
	at com.microsoft.azure.functions.worker.binding.BindingDataStore.getDataByType(BindingDataStore.java:58)
	at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:65)
	at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:42)
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:52)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:51)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

#### Expected behavior

The user details passed on though "userDTO" should be saved successfully in the cosmosdb table. 

#### Actual behavior

I get the Exception mentioned above. 

#### Related information 

* Programming language used is Java

**Comment by kaibocai** [comment]
Hey @Ajay-Negi , thanks for reaching out and sorry for the late reply. 
The only paramter that doesn't needed annotated with `azure-function-java-library` annotations is the `ExecutionContext`. You should never put another paramter without annotations in your funciton (in your case `userDTO`). That's why you encounter the exception you saw. To pass the `userDTO` to your function you should put it in your HTTP request body and send that request to your function app and get the value from the `request` object. 

[Here are more samples](https://github.com/Azure-Samples/azure-functions-samples-java) you can find for using triggers and bindings. We have triggers and bindings for cosmosdb and you can utlizie it to persist your data through azure functions.
