### ISSUE TITLE
Error with Httptrigger for Java function 

### ISSUE THREAD

**Issue by svangeti** [Azure/azure-functions-java-worker#335]
#### Investigative information
I am getting below error with Java function and httpTrigger on my local. The signature of the function as follows.

_> Executing 'Functions.extractText' (Reason='This function was programmatically called via the host APIs.', Id=ae9a89d0-be6c-4faa-b61c-085fc195c99f)
> [11/13/19 12:22:12 AM] Executed 'Functions.extractText' (Failed, Id=ae9a89d0-be6c-4faa-b61c-085fc195c99f)
> [11/13/19 12:22:12 AM] System.Private.CoreLib: Exception while executing function: Functions.extractText. System.Private.CoreLib: Result: Failure
> [11/13/19 12:22:12 AM] Exception: ClassCastException: com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource cannot be cast to java.lang.String
> [11/13/19 12:22:12 AM] Stack: java.lang.ClassCastException: com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource cannot be cast to java.lang.String
> [11/13/19 12:22:12 AM]  at com.microsoft.azure.functions.worker.binding.DataOperations.apply(DataOperations.java:99)
> [11/13/19 12:22:12 AM]  at com.microsoft.azure.functions.worker.binding.DataSource.computeByType(DataSource.java:56)
> [11/13/19 12:22:12 AM]  at com.microsoft.azure.functions.worker.binding.BindingDataStore.getDataByType(BindingDataStore.java:63)
> [11/13/19 12:22:12 AM]  at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:65)
> [11/13/19 12:22:12 AM]  at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:42)
> [11/13/19 12:22:12 AM]  at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:52)
> [11/13/19 12:22:12 AM]  at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:53)
> [11/13/19 12:22:12 AM]  at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
> [11/13/19 12:22:12 AM]  at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
> [11/13/19 12:22:12 AM]  at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
> [11/13/19 12:22:12 AM]  at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
> [11/13/19 12:22:12 AM]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [11/13/19 12:22:12 AM]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [11/13/19 12:22:12 AM]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [11/13/19 12:22:12 AM]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [11/13/19 12:22:12 AM]  at java.lang.Thread.run(Thread.java:748)_

#### Repro steps

Run the function locally and execute with HTTP endpoint with curl command

#### Expected behavior

Function should execute successfully 

#### Actual behavior

The request is not even going into function.

#### Known workarounds

No workarounds

#### Related information 

Provide any related information 

* Programming language used : Java
* Links to source
* Bindings used: 
```
 "bindings": [
      {
        "type": "httpTrigger",
        "name": "content",
        "direction": "in",
        "dataType": "binary",
        "path": "tikaupload/upload.bin",
        "authLevel": "function",
        "methods": [ "post" ]
      },
      {
        "type": "http",
        "name": "$return",
        "direction": "out"
      }
    ]
```

```Java
package azure-testfunctions;
import org.apache.tika.exception.TikaException;
import org.apache.tika.io.TikaInputStream;
import org.apache.tika.metadata.Metadata;
import org.apache.tika.parser.AutoDetectParser;
import org.apache.tika.parser.ParseContext;
import org.apache.tika.sax.BodyContentHandler;
import org.xml.sax.SAXException;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;

import java.util.*;
import com.microsoft.azure.functions.annotation.*;
import com.microsoft.azure.functions.*;
public TikaResponse extractText(byte[] content, final ExecutionContext context)
            throws TikaException, SAXException, IOException {
        context.getLogger().info("javaTika Called");

        AutoDetectParser parser = new AutoDetectParser();
        BodyContentHandler handler = new BodyContentHandler();
        Metadata metadata = new Metadata();
        ParseContext parseContext = new ParseContext();

        InputStream inputStream = new ByteArrayInputStream(content);

        InputStream stream = TikaInputStream.get(inputStream);
        parser.parse(stream, handler, metadata, parseContext);

        return new TikaResponse(metadata, handler.toString());
    }

```

**Comment by amamounelsayed** [comment]
@svangeti Can you please share the all code? Thank you so much

**Comment by Andycharalambous** [comment]
@svangeti did you resolve this eventually? I've just started working with azure functions in java and have hit the exact same problem.

**Comment by kaibocai** [comment]
Hi @svangeti , @Andycharalambous , thanks for reaching out. Are you still get this issue. If yes can you provide a repo that we can used to reproduce the issue. You can find more azure functions java samples [here](https://github.com/Azure-Samples/azure-functions-samples-java/tree/master/src/main/java/com/functions). Thank you.
