### ISSUE TITLE
Error using proxies.json (in latest core tools) :IllegalArgumentException: "" is not a qualified JAR file name

### ISSUE THREAD

**Issue by kulkarnisonia16** [Azure/azure-functions-java-worker#350]
[3/3/2020 8:59:13 PM] Worker failed to function id cb64c890-0460-4c8a-a505-5abe6eec827d.
[3/3/2020 8:59:13 PM] Result: Failure
[3/3/2020 8:59:13 PM] Exception: IllegalArgumentException: "" is not a qualified JAR file name
[3/3/2020 8:59:13 PM] Stack: java.lang.IllegalArgumentException: "" is not a qualified JAR file name
[3/3/2020 8:59:13 PM]   at com.microsoft.azure.functions.worker.description.FunctionMethodDescriptor.guardAgainstUnqualifiedJarPath(FunctionMethodDescriptor.java:141)
[3/3/2020 8:59:13 PM]   at com.microsoft.azure.functions.worker.description.FunctionMethodDescriptor.validate(FunctionMethodDescriptor.java:106)
[3/3/2020 8:59:13 PM]   at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.loadMethod(JavaFunctionBroker.java:31)
[3/3/2020 8:59:13 PM]   at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:27)
[3/3/2020 8:59:13 PM]   at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:9)
[3/3/2020 8:59:13 PM]   at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[3/3/2020 8:59:13 PM]   at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[3/3/2020 8:59:13 PM]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[3/3/2020 8:59:13 PM]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[3/3/2020 8:59:13 PM]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[3/3/2020 8:59:13 PM]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[3/3/2020 8:59:13 PM]   at java.lang.Thread.run(Thread.java:748)
[3/3/2020 8:59:13 PM] .

**Comment by amamounelsayed** [comment]
This issue for recent changes in host. It is just errors in the logs but the functionality is still working.

**Comment by anthonychu** [comment]
I just ran into this as well.

Possibly related: https://github.com/Azure/azure-functions-host/issues/4809

@apawast @amamounelsayed @anirudhgarg Can confirm that the app still works, but would be great if we can fix. Thanks.

**Comment by amamounelsayed** [comment]
@anthonychu this Azure/azure-functions-host#4809 is not related. The function should still work. 
We may need to work with the host to not raise exception in this case as it can be confusing to customers.

Is your function not working?

**Comment by anthonychu** [comment]
Yes it's functional (same as the Node.js issue). But could be alarming for folks to see this.

**Comment by kamperiadis** [comment]
Marking as closed since it does not prevent functions from working.
