### ISSUE TITLE
Jackson serialization BUG with @JsonTypeInfo

### ISSUE THREAD

**Issue by RicardoNiepel** [Azure/azure-functions-java-worker#39]
We've updated our function to jackson 2.9.2.
After that we were still able to run it locally with Azure Functions beta.18.
After  updated to Azure Functions beta.21 and run it locally or at Azure, we got the following exception:

If we delete `@JsonTypeInfo` it succeeds, but we will need this annotation for our application

```
[12/05/2017 10:08:23] ### parent JSON: {"_typeName":"com.xxx.iot.azure.xxx.discovery.Parent","parentInt":42}
[12/05/2017 10:08:23] A ScriptHost error has occurred
[12/05/2017 10:08:23] Exception while executing function: Functions.discover. System.Private.CoreLib: Result: Could not resolve type id 'com.xxx.iot.azure.xxx.discovery.Parent' as a subtype of [simple type, class com.xxx.iot.azure.xxx.discovery.Parent]: no such class found
[12/05/2017 10:08:23]  at [Source: (String)"{"_typeName":"com.xxx.iot.azure.xxx.discovery.Parent","parentInt":42}"; line: 1, column: 14]
[12/05/2017 10:08:23] Exception: Could not resolve type id 'com.xxx.iot.azure.xxx.discovery.Parent' as a subtype of [simple type, class com.xxx.iot.azure.xxx.discovery.Parent]: no such class found
[12/05/2017 10:08:23]  at [Source: (String)"{"_typeName":"com.xxx.iot.azure.xxx.discovery.Parent","parentInt":42}"; line: 1, column: 14]
[12/05/2017 10:08:23] Stack: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'com.xxx.iot.azure.xxx.discovery.Parent' as a subtype of [simple type, class com.xxx.iot.azure.xxx.discovery.Parent]: no such class found
[12/05/2017 10:08:23]  at [Source: (String)"{"_typeName":"com.xxx.iot.azure.xxx.discovery.Parent","parentInt":42}"; line: 1, column: 14]
[12/05/2017 10:08:23]      at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
[12/05/2017 10:08:23]      at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:1628)
[12/05/2017 10:08:23]      at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1186)
[12/05/2017 10:08:23]      at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:51)
[12/05/2017 10:08:23]      at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:42)
[12/05/2017 10:08:23]      at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:156)
[12/05/2017 10:08:23]      at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113)
[12/05/2017 10:08:23]      at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
[12/05/2017 10:08:23]      at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1156)
[12/05/2017 10:08:23]      at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68)
[12/05/2017 10:08:23]      at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
[12/05/2017 10:08:23]      at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
[12/05/2017 10:08:23]      at com.xxx.iot.azure.xxx.discovery.FunctionDiscoveryDirectory.discover(FunctionDiscoveryDirectory.java:58)
```

Our code:

```
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "_typeName")
public class Parent {
       public int parentInt;
       public Parent() {}
       public Parent(int parentInt) {
              this.parentInt = parentInt;
       }
}

ObjectMapper mapper = new ObjectMapper();
Parent parent = new Parent(42);
String parentJson = mapper.writeValueAsString(parent); // OK
context.getLogger().info("### parent JSON: " + parentJson);
Parent parentDeserialized = mapper.readValue(parentJson, Parent.class); // com.fasterxml.jackson.databind.exc.InvalidTypeIdException
context.getLogger().info("### parent deserialized: " + parentDeserialized);
```

**Comment by JunyiYi** [comment]
Hi @RicardoNiepel , can you confirm whether your problem is solved by using the ["lib/" dependency folder](https://github.com/Azure/azure-functions-java-worker/blob/dev/README.md#2-dependencies-in-the-lib-folder)?

**Comment by JunyiYi** [comment]
Close this issue since there are no reponse for more than 2 weeks.
