### ISSUE TITLE
Cosmos, Key Vault, and Function Packages Causing io.netty error

### ISSUE THREAD

**Issue by wjohnson** [Azure/azure-functions-java-worker#397]
When using the Azure Java function template produced by VS Code and after adding Cosmos DB and Azure Key Vault Java SDKs to the pom.xml, the 

#### Investigative information

Please provide the following:

Debugging locally on Windows 10

- Timestamp: N/A
- Function App name: N/A
- Function name(s) (as appropriate): N/A
- Invocation ID: N/A
- Region: N/A

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create an Azure Java Function project using VS Code.
1. Update the settings.json to reflect a Java 11 home path.
1. Add the following to the Pom.xml file
    ```
    <!-- https://mvnrepository.com/artifact/com.azure/azure-cosmos -->
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-cosmos</artifactId>
            <version>4.3.1</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.azure/azure-identity -->
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.1.0</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.azure/azure-security-keyvault-secrets -->
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-security-keyvault-secrets</artifactId>
            <version>4.2.0</version>
        </dependency>
    ```
1. Add the function code below to your Function.java file (in the Related Information section).
1. Run the debugger.
1. Attempt to run a GET request on the localhost endpoint.

#### Expected behavior

Successfully builds the application and is able to extract a key vault secret and connect to a cosmos db database and container.

#### Actual behavior

An exception occurs on `io.netty.handler.ssl.SslProvider.isAlpnSupported`.

```
[8/24/2020 9:50:47 PM] Java HTTP trigger processed a request.
[8/24/2020 9:50:47 PM] Key Vault Name
[8/24/2020 9:50:47 PM] Get credential
[8/24/2020 9:50:48 PM] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[8/24/2020 9:50:48 PM] SLF4J: Defaulting to no-operation (NOP) logger implementation
[8/24/2020 9:50:48 PM] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[8/24/2020 9:50:49 PM] Create Secret client
[8/24/2020 9:50:49 PM] Getting the secret
[8/24/2020 9:50:50 PM] Executed 'Functions.HttpExample' (Failed, Id=036f9e74-f5e4-4f99-a445-bf44d53d215f, Duration=3435ms)
[8/24/2020 9:50:50 PM] System.Private.CoreLib: Exception while executing function: Functions.HttpExample. System.Private.CoreLib: Result: Failure
Exception: NoSuchMethodError: 'boolean io.netty.handler.ssl.SslProvider.isAlpnSupported(io.netty.handler.ssl.SslProvider)'
Stack: java.lang.reflect.InvocationTargetException
[8/24/2020 9:50:50 PM]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[8/24/2020 9:50:50 PM]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[8/24/2020 9:50:50 PM]  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)     
[8/24/2020 9:50:50 PM]  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[8/24/2020 9:50:50 PM]  at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)        
[8/24/2020 9:50:50 PM]  at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
[8/24/2020 9:50:50 PM]  at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:52)
[8/24/2020 9:50:50 PM]  at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[8/24/2020 9:50:50 PM]  at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[8/24/2020 9:50:50 PM]  at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[8/24/2020 9:50:50 PM]  at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[8/24/2020 9:50:50 PM]  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[8/24/2020 9:50:50 PM]  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[8/24/2020 9:50:50 PM]  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[8/24/2020 9:50:50 PM]  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[8/24/2020 9:50:50 PM]  at java.base/java.lang.Thread.run(Thread.java:834)
[8/24/2020 9:50:51 PM] Caused by: java.lang.NoSuchMethodError: 'boolean io.netty.handler.ssl.SslProvider.isAlpnSupported(io.netty.handler.ssl.SslProvider)'
[8/24/2020 9:50:51 PM]  at reactor.netty.http.client.HttpClientSecure.<clinit>(HttpClientSecure.java:79)
[8/24/2020 9:50:51 PM]  at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:304)
[8/24/2020 9:50:51 PM]  at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
[8/24/2020 9:50:51 PM]  at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:79)
[8/24/2020 9:50:51 PM]  at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
[8/24/2020 9:50:51 PM]  at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
[8/24/2020 9:50:51 PM]  at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:329)
[8/24/2020 9:50:51 PM]  at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
[8/24/2020 9:50:51 PM]  at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
[8/24/2020 9:50:51 PM]  at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
[8/24/2020 9:50:51 PM]  at reactor.core.publisher.Mono.block(Mono.java:1679)
[8/24/2020 9:50:51 PM]  at com.azure.security.keyvault.secrets.SecretClient.getSecretWithResponse(SecretClient.java:171)
[8/24/2020 9:50:51 PM]  at com.azure.security.keyvault.secrets.SecretClient.getSecret(SecretClient.java:150)
[8/24/2020 9:50:51 PM]  at com.walgreens.Function.run(Function.java:63)
[8/24/2020 9:50:51 PM]  ... 16 more
[8/24/2020 9:50:51 PM] .
[8/24/2020 9:50:51 PM] Executed HTTP request: {
[8/24/2020 9:50:51 PM]   requestId: "f8163aa7-4706-4b26-833d-76f20f0f833c",
[8/24/2020 9:50:51 PM]   identities: "",
[8/24/2020 9:50:51 PM]   status: "500",
[8/24/2020 9:50:52 PM]   duration: "5241"
[8/24/2020 9:50:52 PM] }
```
#### Known workarounds

Unknown

#### Related information 

Provide any related information 

* Programming language used: Java
* Bindings used: HTTP Trigger

I also attempted to use the shading as referenced in #381 but I still had the same netty error.  It was like the shaded jars were not even being referenced during runtime.

<details>
<summary>Source</summary>

```java
package com.mycompany;

import com.microsoft.azure.functions.ExecutionContext;
import com.microsoft.azure.functions.HttpMethod;
import com.microsoft.azure.functions.HttpRequestMessage;
import com.microsoft.azure.functions.HttpResponseMessage;
import com.microsoft.azure.functions.HttpStatus;
import com.microsoft.azure.functions.annotation.AuthorizationLevel;
import com.microsoft.azure.functions.annotation.FunctionName;
import com.microsoft.azure.functions.annotation.HttpTrigger;

import java.util.Optional;

import com.azure.identity.DefaultAzureCredential;
import com.azure.identity.DefaultAzureCredentialBuilder;
import com.azure.security.keyvault.secrets.SecretClient;
import com.azure.security.keyvault.secrets.SecretClientBuilder;

import com.azure.cosmos.CosmosClient;
import com.azure.cosmos.CosmosContainer;
import com.azure.cosmos.CosmosDatabase;
import com.azure.cosmos.CosmosClientBuilder;
import com.azure.cosmos.models.CosmosContainerProperties;
import com.azure.cosmos.models.CosmosContainerResponse;
import com.azure.cosmos.models.CosmosDatabaseResponse;
import com.azure.cosmos.models.CosmosItemRequestOptions;
import com.azure.cosmos.models.CosmosItemResponse;

public class Function {

    @FunctionName("HttpExample")
    public HttpResponseMessage run(
            @HttpTrigger(
                name = "req",
                methods = {HttpMethod.GET, HttpMethod.POST},
                authLevel = AuthorizationLevel.ANONYMOUS)
                HttpRequestMessage<Optional<String>> request,
            final ExecutionContext context) {
        context.getLogger().info("Java HTTP trigger processed a request.");

        SecretClient secretClient;
        String keyVaultUrl;
        CosmosClient cosmosClient;

        context.getLogger().info("Key Vault Name");
        String keyVaultName = System.getenv("KEY_VAULT_NAME");
        keyVaultUrl = (new StringBuilder().append("https://").append(keyVaultName).append(".vault.azure.net/"))
                .toString();
        
        context.getLogger().info("Get credential");
        DefaultAzureCredential creds = new DefaultAzureCredentialBuilder().build();
        context.getLogger().info("Create Secret client");
        secretClient = new SecretClientBuilder().vaultUrl(keyVaultUrl).credential(creds).buildClient();
        context.getLogger().info("Getting the secret");
        String cosmosConnString = secretClient.getSecret("CosmosConnStrRWWithAppDB").getValue();
        
        context.getLogger().info("Splitting up the conn string");
        String[] connStringParts = cosmosConnString.split(";");
        String cosmosHost = "";
        String cosmosKey = "";

        // Pick out the pieces from the connection string
        for (String part : connStringParts) {
            final String ENDPOINTNAME = "AccountEndpoint=";
            final String KEYNAME = "AccountKey=";
            if (part.startsWith(ENDPOINTNAME)) {
                cosmosHost = part.substring(ENDPOINTNAME.length(), part.length());
            } else if (part.startsWith(KEYNAME)) {
                cosmosKey = part.substring(KEYNAME.length(), part.length());
            }
        }

        context.getLogger().info("Creating Cosmos Client");
        // Cosmos Client
        cosmosClient = new CosmosClientBuilder().endpoint(cosmosHost).key(cosmosKey).buildClient();
        
        context.getLogger().info("Creating Cosmos DB and Container");
        CosmosDatabase db = cosmosClient.getDatabase("ControlDatabase");
        CosmosContainer con = db.getContainer("ControlTable");

        // Parse query parameter
        final String query = request.getQueryParameters().get("name");
        final String name = request.getBody().orElse(query);

        if (name == null) {
            return request.createResponseBuilder(HttpStatus.BAD_REQUEST).body("Please pass a name on the query string or in the request body").build();
        } else {
            return request.createResponseBuilder(HttpStatus.OK).body("Hello, " + name).build();
        }
    }
}
```
</details>

**Comment by amamounelsayed** [comment]
Thank you so much @wjohnson the reason I believe the issue cause is that we did not release yet with the coretools. 
It is already release for runtime. 

We are keeping the https://github.com/Azure/azure-functions-java-worker/issues/381 update it with this info

**Comment by wjohnson** [comment]
Got it! Thank you for the clarification @amamounelsayed !

We found a workaround for our particular use case in using Azure Key Vault references rather than the Azure Key Vault SDK.  After removing the Key Vault SDK, I was able to get the Cosmos SDK portions to work without the current issue.

**Comment by amamounelsayed** [comment]
Sounds good thank you so much @wjohnson . We should have the core tools deploy sometime soon. I will keep the thread update it.

**Comment by amamounelsayed** [comment]
@wjohnson thank you so much for your time.

Core tools have been release
v3 3.0.2852 or higher
v2 2.7.2855 or higher

https://github.com/Azure/azure-functions-core-tools/releases
