### ISSUE TITLE
Cannot convert binding.RpcHttpRequestDataSource to HttpRequestMessage<Optional<List<EventGridEvent>>>

### ISSUE THREAD

**Issue by Shrirang97** [Azure/azure-functions-java-worker#477]
I have created HttpTrigger Azure Function.  I am calling by HTTP post request with body

> [
          {
              "topic": "string",
              "subject": "string",
              "id": "string",
              "eventType": "UsageDetail",
              "data": {},
              "dataVersion": "string",
              "metadataVersion": "string"
            }
]

But I am getting following error locally when post request through postman
`Exception: ClassCastException: Cannot convert com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource@2a316285to type com.microsoft.azure.functions.HttpRequestMessage<java.util.Optional<java.util.List<com.azure.messaging.eventgrid.EventGridEvent>>>`

#### Investigative information

Please provide the following:

- Timestamp:
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

> 2021-10-21T16:33:50.883 [Information] Executing 'Functions.UsageDetailPublisherFunction' (Reason='This function was programmatically called via the host APIs.', Id=cb0c1680-de0c-4952-8047-0a0122cbdfc3)
2021-10-21T16:33:51.449 [Information] [com.azure.messaging.eventgrid.EventGridEvent@4b59984e]
2021-10-21T16:33:51.456 [Information] 1
2021-10-21T16:33:51.483 [Error] Executed 'Functions.UsageDetailPublisherFunction' (Failed, Id=cb0c1680-de0c-4952-8047-0a0122cbdfc3, Duration=597ms)Result: FailureException: NullPointerException:Stack: java.lang.reflect.InvocationTargetExceptionat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:566)at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:57)at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)at java.base/java.lang.Thread.run(Thread.java:834)Caused by: java.lang.NullPointerExceptionat com.azure.messaging.eventgrid.EventGridEvent.getEventType(EventGridEvent.java:248)at com.iluwatar.producer.calldetails.functions.UsageDetailPublisherFunction.run(UsageDetailPublisherFunction.java:43)... 16 more

#### Repro steps
Send HTTP post request

#### Expected behavior
200 OK result

#### Actual behavior
Exception

#### Related information 
* Programming language used : Java 11
* Links to source : 

``` JAVA 11
 
    public class Azure Function {
        @FunctionName("AzureFunction")
        public HttpResponseMessage run(@HttpTrigger(name = "request", methods = { HttpMethod.GET,
                HttpMethod.POST }, authLevel = AuthorizationLevel.ANONYMOUS) HttpRequestMessage<Optional<List<EventGridEvent>>> request,
                final ExecutionContext context) {
  
          context.getLogger().info(request.getBody().get().toString());
          context.getLogger().info(request.getBody().get().size() + "");
          List<EventGridEvent> eventGridEvents = (ArrayList<EventGridEvent>) request.getBody().get();

        for (EventGridEvent eventGridEvent : eventGridEvents) {
            // Handle system events
              if (eventGridEvent.getEventType().equals("Microsoft.EventGrid.SubscriptionValidationEvent")) {
                  SubscriptionValidationEventData subscriptionValidationEventData = eventGridEvent.getData()
                          .toObject(SubscriptionValidationEventData.class);
                  // Handle the subscription validation event
                  SubscriptionValidationResponse responseData = new SubscriptionValidationResponse();
                  responseData.setValidationResponse(subscriptionValidationEventData.getValidationCode());
                  return request.createResponseBuilder(HttpStatus.OK).body(responseData).build();
             }
          }
           return request.createResponseBuilder(HttpStatus.OK).body(null).build();
    }
}

```

https://github.com/Shrirang97/java-design-patterns/blob/claim-check-pattern-azure/claim-check-pattern/Call%20Usage%20App/src/main/java/com/iluwatar/producer/calldetails/functions/UsageDetailPublisherFunction.java

**Comment by Shrirang97** [comment]
@pragnagopa can you please look into this?

**Comment by kaibocai** [comment]
Hi @Shrirang97 , thanks for open this issue, sorry for the late reply as we are full of capacity. The source link you provided is giving 404, would you mind give the latest link for the repo to reproduce this issue. Thanks very much.
