### ISSUE TITLE
Bind message ID from queue trigger

### ISSUE THREAD

**Issue by cb8** [Azure/azure-functions-java-worker#49]
i'd like to bind the message ID from a queue trigger to a parameter:
```java
public class Function {
	@FunctionName("execute")
	@QueueOutput(name = "output", queueName = "results")
	public String execute(@QueueTrigger(name = "input", queueName="inputs") String input, @BindingName("Id") String id) throws IOException {
		// ...
		return "result";
	}
}
```
however, an exception is thrown when a new mesage is received: *Cannot locate the method signature with the given input*. is there a way to bind the ID?

**Comment by JunyiYi** [comment]
@christopheranderson , is storage queue message ID available in trigger metadata?

**Comment by pragnagopa** [comment]
This is a bug. Currently it fails with generic method not found error
```
fail: Function.QueueTriggerMetadata[0]
      Executed 'Functions.QueueTriggerMetadata' (Failed, Id=ef2a0633-e7e8-42af-b5ed-86c1ebb69e22)
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.QueueTriggerMetadata ---> Microsoft.Azure.WebJobs.Script.Rpc.RpcException: Result: Failure
Exception: NoSuchMethodException: Cannot locate the method signature with the given input
Stack: java.lang.NoSuchMethodException: Cannot locate the method signature with the given input
        at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.lambda$execute$0(JavaMethodExecutor.java:49)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:49)
        at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:47)
        at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
        at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
        at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
        at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:91)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
