### ISSUE TITLE
Receiving a NullPointerException while attempting to test local RabbitMQOutput

### ISSUE THREAD

**Issue by eborisow** [Azure/azure-functions-java-worker#577]
I've setup a basic Azure function with the @TimerTrigger and @RabbitMQOutput annotations as mentioned here:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-rabbitmq?tabs=in-process&pivots=programming-language-java

```
public class RabbitMQFunction {
        private static final Logger logger = LoggerFactory.getLogger(RabbitMQFunction.class);
        /**
         * This function will be invoked periodically according to the specified schedule.
         */
        @FunctionName("RabbitMQFunction")
        public void run(
            @TimerTrigger(name = "timerInfo", schedule = "*/15 * * * * *") String timerInfo,
            @RabbitMQOutput(connectionStringSetting = "rabbitMQConnectionAppSetting", queueName = "myQueue", disableCertificateValidation = true) OutputBinding<String> output,
            final ExecutionContext context
        ) {
            logger.debug("START - RabbitMQFunction");
            context.getLogger().info("Java Timer trigger function executed at: " + LocalDateTime.now());
            output.setValue("Some string");
            logger.debug("END - RabbitMQFunction");
        }
    }
```

Unfortunately, I'm receiving the following error in the output when testing locally with Azurite in Visual Studio Code.  Here's the stack trace:

```
[2022-05-24T13:46:48.878Z] Received FunctionLoadResponse for function: 'RabbitMQFunction' with functionId: 'b09d265b-8b35-478f-8657-da7cf5b0fbc6'.
    [2022-05-24T13:46:49.529Z] Host lock lease acquired by instance ID '000000000000000000000000CEA4F55C'.
    [2022-05-24T13:47:00.087Z] Executing 'Functions.RabbitMQFunction' (Reason='Timer fired at 2022-05-24T09:47:00.0322362-04:00', Id=a34b49d5-603f-4977-92f0-672f0d5feb86)
    [2022-05-24T13:47:00.243Z] InvocationResponse received for invocation id: 'a34b49d5-603f-4977-92f0-672f0d5feb86'
    [2022-05-24T13:47:00.325Z] Executed 'Functions.RabbitMQFunction' (Failed, Id=a34b49d5-603f-4977-92f0-672f0d5feb86, Duration=265ms)
    [2022-05-24T13:47:00.327Z] System.Private.CoreLib: Exception while executing function: Functions.RabbitMQFunction. System.Private.CoreLib: Result: Failure
    Exception: NullPointerException:
    Stack: java.lang.NullPointerException
    [2022-05-24T13:47:00.329Z]      at com.microsoft.azure.functions.worker.binding.BindingDataStore.isDataTargetValid(BindingDataStore.java:145)       
    [2022-05-24T13:47:00.331Z]      at com.microsoft.azure.functions.worker.binding.BindingDataStore.getOrAddDataTarget(BindingDataStore.java:123)      
    [2022-05-24T13:47:00.333Z]      at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:56)
    [2022-05-24T13:47:00.334Z]      at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:42)
    [2022-05-24T13:47:00.336Z]      at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:53)
    [2022-05-24T13:47:00.338Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:61)
    [2022-05-24T13:47:00.339Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)  
    [2022-05-24T13:47:00.341Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)  
    [2022-05-24T13:47:00.342Z]      at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
    [2022-05-24T13:47:00.344Z]      at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
    [2022-05-24T13:47:00.345Z]      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    [2022-05-24T13:47:00.347Z]      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    [2022-05-24T13:47:00.349Z]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    [2022-05-24T13:47:00.351Z]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    [2022-05-24T13:47:00.352Z]      at java.base/java.lang.Thread.run(Thread.java:829)
    [2022-05-24T13:47:00.354Z] .
```

host.json contains:

```
{
      "version": "2.0",
      "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[3.3.0, 4.0.0)"
      }
```

local.settings.json contains:

```
{
      "IsEncrypted": false,
      "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=true",
        "FUNCTIONS_WORKER_RUNTIME": "java",
        "rabbitMQConnectionAppSetting": "amqp://guest:guest@127.0.0.1:5672/"
      }
    }
```

build.gradle contains:

```
implementation 'com.microsoft.azure.functions:azure-functions-java-library:2.0.1'
    implementation 'com.microsoft.azure.functions:azure-functions-java-library-rabbitmq:1.0.0'
    // I've also tried with 2.0.0-preview
```

Question was also posted to StackOverFlow:
https://stackoverflow.com/questions/72368047

**Comment by kaibocai** [comment]
Hi @eborisow , thanks very much for open this issue. Would you mind provided a repo that we can use to reproduce the issue, so we can focus on fixing the issue instead of set up/configuration. Thank you.

**Comment by kaibocai** [comment]
Hi @eborisow , thanks very much for open this issue. Can you make sure you have the right host.json configuration set up. More details can be find [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-rabbitmq-trigger?tabs=in-process&pivots=programming-language-java#hostjson-settings). 
Also can you let me know how you get your rabbitmq connection string? Thank you.
