### ISSUE TITLE
Still facing class cast exception

### ISSUE THREAD

**Issue by AjayAsok** [Azure/azure-functions-java-worker#596]
Hi,
I am facing the ClassCastExeption issue shown below.
Exception: ClassCastException: Cannot convert com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource@1222ab9ato type com.microsoft.azure.functions.HttpRequestMessage<java.util.Optional<com.example.ToDoItem>>
Stack: java.lang.ClassCastException: Cannot convert com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource@1222ab9ato type com.microsoft.azure.functions.HttpRequestMessage<java.util.Optional<com.example.ToDoItem>>
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.binding.DataOperations.generalAssignment(DataOperations.java:191)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.binding.DataOperations.apply(DataOperations.java:120)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.binding.DataSource.computeByType(DataSource.java:56)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource.computeByType(RpcHttpRequestDataSource.java:20)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.binding.DataSource.computeByName(DataSource.java:42)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource.computeByName(RpcHttpRequestDataSource.java:20)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.binding.BindingDataStore.getDataByName(BindingDataStore.java:62)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:59)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:42)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:53)
[2022-06-27T09:50:50.645Z] 	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:61)
[2022-06-27T09:50:50.646Z] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2022-06-27T09:50:50.646Z] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2022-06-27T09:50:50.646Z] 	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2022-06-27T09:50:50.646Z] 	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2022-06-27T09:50:50.646Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2022-06-27T09:50:50.646Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2022-06-27T09:50:50.646Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2022-06-27T09:50:50.646Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2022-06-27T09:50:50.646Z] 	at java.base/java.lang.Thread.run(Thread.java:834)
[2022-06-27T09:50:50.646Z] .

I tried using the Sample mentioned in [https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=in-process%2Cfunctionsv2&pivots=programming-language-java](url) .

```
@FunctionName("TriggerPojoPost")
	public HttpResponseMessage run1(@HttpTrigger(name = "req", methods = {
			HttpMethod.POST }, authLevel = AuthorizationLevel.ANONYMOUS) HttpRequestMessage<Optional<ToDoItem>> request,
			final ExecutionContext context) {
		context.getLogger().info("Request body is: " + request.getBody());
		Optional<ToDoItem> r = request.getBody();
		ToDoItem theObj = (ToDoItem) r.get();
		context.getLogger().info("Request body is: " + theObj);
		// Item list
		context.getLogger().info("Request body is: " + request.getBody().orElse(null));

		// Check request body
		if (!request.getBody().isPresent()) {
			return request.createResponseBuilder(HttpStatus.BAD_REQUEST).body("Document not found.").build();
		} else {
			// return JSON from to the client
			// Generate document
			final ToDoItem body = (ToDoItem) request.getBody().get();
			return request.createResponseBuilder(HttpStatus.OK).header("Content-Type", "application/json").body(body)
					.build();
		}
	}
```

Could anyone please help me on this?

_Originally posted by @AjayAsok in https://github.com/Azure/azure-functions-java-worker/issues/255#issuecomment-1167141297_

**Comment by kaibocai** [comment]
Hi @AjayAsok , thanks for reaching out. Can you provide the post request you send to you function, also can you let us know how you defined your ToDoItem class. A repo that can be used to reproduce the issue with all those info I asked will be very helpful for us to identify your issue, instead of wasting time on minor configs. Thank you.

**Comment by AjayAsok** [comment]
Hi @kaibocai, Thank you so much for your response. It worked in my colleagues system perfectly without. I have copied the same and works for me as well. I guess this is something with the version mismatch or with my environment. Thank you so much for your time.

**Comment by per-steinar** [comment]
I had a similar issue with Azure Functions on Java 17. I had to add  the following app_settings:
`languageWorkers__java__arguments = "--add-opens java.base/java.time=ALL-UNNAMED"`
Notice the double _
