### ISSUE TITLE
JSON Validation error yields HTTP 500

### ISSUE THREAD

**Issue by Clockwork-Muse** [Azure/azure-functions-java-worker#62]
[minimal repro project](https://github.com/Azure/azure-functions-java-worker/files/1750008/malformed-json.zip)

Start it up via the usual methods, then send:
```json
{
	"keyValue":"asdasd"
}
```
(there's a missing `other` required property)
This _should_ result in an HTTP 400 error.  Instead, it punts back an HTTP 500:
> [2018-02-23 00:16:02] A ScriptHost error has occurred
[2018-02-23 00:16:02] Exception while executing function: Functions.hello. System.Private.CoreLib: Result: Cannot locate the method signature with the given input
Exception: Cannot locate the method signature with the given input
Stack: java.lang.NoSuchMethodException: Cannot locate the method signature with the given input
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.lambda$execute$0(JavaMethodExecutor.java:58)
[2018-02-23 00:16:02]   at java.base/java.util.Optional.orElseThrow(Optional.java:385)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:58)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:40)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.handler.MessageHandler.handle(MessageHandler.java:43)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:84)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1393)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[2018-02-23 00:16:02] .
[2018-02-23 00:16:02] Exception while executing function: Functions.hello. System.Private.CoreLib: Result: Cannot locate the method signature with the given input
Exception: Cannot locate the method signature with the given input
Stack: java.lang.NoSuchMethodException: Cannot locate the method signature with the given input
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.lambda$execute$0(JavaMethodExecutor.java:58)
[2018-02-23 00:16:02]   at java.base/java.util.Optional.orElseThrow(Optional.java:385)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:58)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:40)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.handler.MessageHandler.handle(MessageHandler.java:43)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:84)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1393)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[2018-02-23 00:16:02] .
[2018-02-23 00:16:02]
[2018-02-23 00:16:02] Exception while executing function: Functions.hello
[2018-02-23 00:16:02] Exception while executing function: Functions.hello. System.Private.CoreLib: Result: Cannot locate the method signature with the given input
Exception: Cannot locate the method signature with the given input
Stack: java.lang.NoSuchMethodException: Cannot locate the method signature with the given input
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.lambda$execute$0(JavaMethodExecutor.java:58)
[2018-02-23 00:16:02]   at java.base/java.util.Optional.orElseThrow(Optional.java:385)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:58)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:40)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.handler.MessageHandler.handle(MessageHandler.java:43)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:84)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1393)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[2018-02-23 00:16:02] .
[2018-02-23 00:16:02] Function completed (Failure, Id=16ddb322-1f6c-45e9-9cdf-b8e73f8ff450, Duration=181ms)
[2018-02-23 00:16:02]
[2018-02-23 00:16:02] Executed 'Functions.hello' (Failed, Id=16ddb322-1f6c-45e9-9cdf-b8e73f8ff450)
[2018-02-23 00:16:02] System.Private.CoreLib: Exception while executing function: Functions.hello. System.Private.CoreLib: Result: Cannot locate the method signature with the given input
Exception: Cannot locate the method signature with the given input
Stack: java.lang.NoSuchMethodException: Cannot locate the method signature with the given input
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.lambda$execute$0(JavaMethodExecutor.java:58)
[2018-02-23 00:16:02]   at java.base/java.util.Optional.orElseThrow(Optional.java:385)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:58)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:40)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.handler.MessageHandler.handle(MessageHandler.java:43)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:84)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1393)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[2018-02-23 00:16:02] .
[2018-02-23 00:16:02]   Function had errors. See Azure WebJobs SDK dashboard for details. Instance ID is '16ddb322-1f6c-45e9-9cdf-b8e73f8ff450'
[2018-02-23 00:16:02] System.Private.CoreLib: Exception while executing function: Functions.hello. System.Private.CoreLib: Result: Cannot locate the method signature with the given input
Exception: Cannot locate the method signature with the given input
Stack: java.lang.NoSuchMethodException: Cannot locate the method signature with the given input
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.lambda$execute$0(JavaMethodExecutor.java:58)
[2018-02-23 00:16:02]   at java.base/java.util.Optional.orElseThrow(Optional.java:385)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:58)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:40)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.handler.MessageHandler.handle(MessageHandler.java:43)
[2018-02-23 00:16:02]   at com.microsoft.azure.webjobs.script.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:84)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1393)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
[2018-02-23 00:16:02]   at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[2018-02-23 00:16:02] .

This also happens if you provide **no** fields (assuming none are required), which I'm taking more as a symptom of how things were written.

**Comment by JunyiYi** [comment]
This is an expected result (HTTP 500) when no function **signature** is matched, which means the function exists, but the parameter is not able to be converted to the actual type. And HTTP 400 represents that the function itself does not exist.

**Comment by Clockwork-Muse** [comment]
.... Why is 500 an expected result here?  The problem is that the client has made an invalid request (left out some expected field), which is the **client's** fault, not the server's.  A raw 400 sounds like the most relevant option (whereas the function not existing should probably net you a 404).

**Comment by JunyiYi** [comment]
Think about parsing the data by yourself. You accept any Object, and parse it to something like Integer.parse(obj). An exception will be thrown when the input is not an integer, and the server will respond 500. Here we just simulate this behavior, if the input format is wrong, just throw the exception.

**Comment by Clockwork-Muse** [comment]
oookkaayyy, if I'm parsing the object myself (which I'm going to have to do anyways, since the error messages have to be formatted according to corporate standard), if there's an error during the parsing I'm blaming the caller (return a 400), not just throwing up my hands and dying.  This lets them know that **they** did something wrong.  A 500 is **I** did something wrong, and the caller can't fix it (except in the case of 503, where the remedy might be "try again later").

Given your analogy, the closest thing I can think of is getting a _compiler_ error, only it's one of the old C ones that just says "missing end bracket".  It's not really helpful, and doesn't point you towards what, specifically, is wrong with what you just tried to do.  A parsing exception is at least normally going to tell me something like "invalid character", "number too big", or something like that.

**Comment by JunyiYi** [comment]
Well it not just as simple as simple parsing failure. You are allowed to introduce multiple functions with the same name, similar to method overload. Now you invoke the function with the wrong parameters, we treat it just like how java compiler treats it: giving out the error message, "Cannot locate the method." It would be impossible to tell the user which parameter is wrong.

**Comment by Clockwork-Muse** [comment]
That reasoning makes the message "Cannot locate the method" more understandable.  I'm not sure how _common_ that usage will be, but more understandable.

**However**, that's still not a **server** problem.  That's still the client making a poorly formed request.  A client can (presumably trivially) succeed if they adjust their request appropriately, whereas the 500 tells the client "you did everything okay, it's my fault", which is clearly untrue.  I would return only ever return a 500 for things completely outside the client's control - like database connection issues - and never for something under client control (malformed messages, invalid or unauthorized resources).

**Comment by Clockwork-Muse** [comment]
I'm even less enthusiastic about the current status code given how path parameters are handled.

Consider this definition:
```Java
@FunctionName("hello")
public HttpResponseMessage<String> hello(
        @HttpTrigger(name = "req", methods = { "post" }, authLevel = AuthorizationLevel.ANONYMOUS, route = "hello/{id:int}") HttpRequestMessage<String> request,
        @BindingName("id") Optional<Integer> id, final ExecutionContext context) {

    return request.createResponse(200, "Value: " + request.getBody() + "|" + id.get());
}
```

this is reachable via `localhost:7071/api/hello/1`, but `localhost:7071/api/hello/a` generates a 404 (which _is_ what I expect), not a 500/can't find method error. 

<hr />

So what I'd normally expect to see is, at minimum, a 400 error with some sort of "you didn't provide a valid body object" message.  For the **common** case of non-overloaded methods (only a single possibility!), you could list missing/invalid fields.  For the case of overloaded methods, you could potentially list all valid objects (and/or say "you're closest to this one, are you missing this field?").  

Which brings up an excellent question: If overloaded methods have different security requirements, can I use the "invalid object" method to find out they exist?  Or are all functions visible anyways, and I'd be getting 403s?

**Comment by JunyiYi** [comment]
Your HTTP routing example is more complicated. That error is generated by the host (whose job is finding the correct function definition according to the URL); after that, the worker kicks in, and get the knowledge of your function name (which is `hello` in this case) from your `funtions.json` definition. And now the worker will load all methods named `hello` and try to match the parameters.

But you mentioned a good point, maybe we could just change 500 to 404 in the future. 😄

**Comment by Clockwork-Muse** [comment]
A 404 would send people barking up the wrong tree, though.  It would have to be a straight 400; a 404 would make people look at the path, not the object.

**Comment by Clockwork-Muse** [comment]
Hmm, it's not only malformed JSON - passing _any_ form of unmapped input results in the 500, no-matching-method-found, error (ie, passing form input).

**Comment by pragnagopa** [comment]
@Clockwork-Muse - I have PR out to enable relaxed mapping PR #202 This should help.

**Comment by pragnagopa** [comment]
Closing as the linked PR addressed this issue
