### ISSUE TITLE
Spring ApplicationContext XML not found in classpath in Azure Function even though it's there

### ISSUE THREAD

**Issue by damadei** [Azure/azure-functions-java-worker#65]
I've a function using Spring Framework and when I try to get the ApplicationContext using ClasspathXmlApplicationContext and the following line:

ApplicationContext applicationContext = new ClassPathXmlApplicationContext("classpath:/applicationContext.xml");

I get the following exception even tough I see the file in my function JAR's root.

[27/02/2018 20:32:03]   Function had errors. See Azure WebJobs SDK dashboard for details. Instance ID is '2c2dab1a-16ea-469b-98a1-32dbbde405be'
[27/02/2018 20:32:03] System.Private.CoreLib: Exception while executing function: Functions.ReadinessSyncFunction. System.Private.CoreLib: Result: IOException parsing XML document from class path resource [applicationContext.xml]; nested exception is java.io.FileNotFoundException: class path resource [applicationContext.xml] cannot be opened because it does not exist
Exception: IOException parsing XML document from class path resource [applicationContext.xml]; nested exception is java.io.FileNotFoundException: class path resource [applicationContext.xml] cannot be opened because it does not exist
Stack: org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from class path resource [applicationContext.xml]; nested exception is java.io.FileNotFoundException: class path resource [applicationContext.xml] cannot be opened because it does not exist
[27/02/2018 20:32:03]   at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:343)
[27/02/2018 20:32:03]   at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:303)
[27/02/2018 20:32:03]   at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:187)
[27/02/2018 20:32:03]   at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:223)
[27/02/2018 20:32:03]   at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:194)
[27/02/2018 20:32:03]   at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:258)
[27/02/2018 20:32:03]   at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:128)
[27/02/2018 20:32:03]   at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:94)
[27/02/2018 20:32:03]   at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:133)
[27/02/2018 20:32:03]   at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:620)
[27/02/2018 20:32:03]   at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:521)
[27/02/2018 20:32:03]   at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
[27/02/2018 20:32:03]   at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:85)
[27/02/2018 20:32:03]   at br.com.microsoft.ocp.partner.readiness.sync.Function.sync(Function.java:41)
[27/02/2018 20:32:03] Caused by: java.io.FileNotFoundException: class path resource [applicationContext.xml] cannot be opened because it does not exist
[27/02/2018 20:32:03]   at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
[27/02/2018 20:32:03]   at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:329)
[27/02/2018 20:32:03]   at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:303)
[27/02/2018 20:32:03]   at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:187)
[27/02/2018 20:32:03]   at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:223)
[27/02/2018 20:32:03]   at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:194)
[27/02/2018 20:32:03]   at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:258)
[27/02/2018 20:32:03]   at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:128)
[27/02/2018 20:32:03]   at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:94)
[27/02/2018 20:32:03]   at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:133)
[27/02/2018 20:32:03]   at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:620)
[27/02/2018 20:32:03]   at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:521)
[27/02/2018 20:32:03]   at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
[27/02/2018 20:32:03]   at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:85)
[27/02/2018 20:32:03]   at br.com.microsoft.ocp.partner.readiness.sync.Function.sync(Function.java:41)
[27/02/2018 20:32:03]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[27/02/2018 20:32:03]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[27/02/2018 20:32:03]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[27/02/2018 20:32:03]   at java.lang.reflect.Method.invoke(Method.java:498)
[27/02/2018 20:32:03]   at com.microsoft.azure.webjobs.script.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
[27/02/2018 20:32:03]   at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:59)
[27/02/2018 20:32:03]   at com.microsoft.azure.webjobs.script.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:40)
[27/02/2018 20:32:03]   at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[27/02/2018 20:32:03]   at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[27/02/2018 20:32:03]   at com.microsoft.azure.webjobs.script.handler.MessageHandler.handle(MessageHandler.java:43)
[27/02/2018 20:32:03]   at com.microsoft.azure.webjobs.script.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:84)
[27/02/2018 20:32:03]   at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
[27/02/2018 20:32:03]   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[27/02/2018 20:32:03]   at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[27/02/2018 20:32:03]   at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[27/02/2018 20:32:03]   at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[27/02/2018 20:32:03] .

**Comment by JunyiYi** [comment]
Let's try this again after the new "lib/" dependencies feature is published.

**Comment by damadei** [comment]
JunyiYi, the weird thing is that it's not in an external JAR, it's in the root of the application JAR itself, where all classes are being loaded from and where they are being found.

**Comment by kevinhillinger** [comment]
@damadei this reason is because the resource paths don't get registered properly because the fat jar packaging 'conflicts' with springs packaging.

Can you revalidate this change locally? start with a fresh mvn archetype of azure-functions (the latest has the updated plugin config for the /lib folder) or create one and reference. Then update the tools `npm i -g npm` then `npm i -g azure-functions-core-tools@core'. 

The key thing to verify is that /target folder's azure function has a /lib and it's copying things over.

**Comment by kevinhillinger** [comment]
@damadei Can you provide the codebase with the call to get the ApplicationContext? It matters which version of Spring you're using, where the call is being made in the code, etc. Otherwise, I think we should close the ticket @JunyiYi

**Comment by paulbatum** [comment]
Closing this due to inactivity. I can reopen if required.
