### ISSUE TITLE
Unable to retreive Event properties with Azure function. Exception at getTriggerMetatDataByName(BindingDataStore.java:66)

### ISSUE THREAD

**Issue by survivant** [Azure/azure-functions-java-worker#653]
I have IOT Hub that send device events to EventHub using routing.  I have a Azure function that receive those events, but I'm not able to retreive the event headers/properties.  When I device update his properties, I received a event but within that event, the sourceid (deviceid) is not included, so I need to look into IOTHub event's properties to have that information.

here the code that I have
````
public class StringEventHubTriggerFunction extends FunctionInvoker<String, String>{
    private static final Logger LOGGER = LoggerFactory.getLogger(StringEventHubTriggerFunction.class);

    /**
     * This function will be invoked when an event is received from Event Hub.
     */
    @FunctionName("eventhubTriggerDevice")
    public void execute(
            @EventHubTrigger(
                    name = "eventhubTriggerDevice",
                    eventHubName = "iot-to-eventhub-devices",
                    connection = "AzureEventHubConnectionString",
                    consumerGroup = "group-iot",
                    cardinality = Cardinality.ONE)
            String user,
            @BindingName("systemPropertiesArray") SystemProperty[] systemProperties,
            final ExecutionContext context) {
        LOGGER.info("Java Event Hub trigger function executed. Device:[{}]", user);
        handleRequest(user, context);
    }

    public static class SystemProperty {
        public String SequenceNumber;
        public String Offset;
        public String PartitionKey;
        public String EnqueuedTimeUtc;
    }
}
````

the exception generated is this 
````
[2022-09-20T15:57:16.203Z] Executing 'Functions.eventhubTriggerDevice' (Reason='(null)', Id=6df221dd-2334-4594-9a1a-9b0e05e43175)
[2022-09-20T15:57:16.203Z] Trigger Details: PartionId: 2, Offset: 40584, EnqueueTimeUtc: 2022-09-20T15:57:16.1010000+00:00, SequenceNumber: 53, Count: 1
[2022-09-20T15:57:16.208Z] Executed 'Functions.eventhubTriggerDevice' (Failed, Id=6df221dd-2334-4594-9a1a-9b0e05e43175, Duration=5ms)
[2022-09-20T15:57:16.208Z] System.Private.CoreLib: Exception while executing function: Functions.eventhubTriggerDevice. System.Private.CoreLib: Result: Failure
Exception: NullPointerException: 
Stack: java.lang.NullPointerException
[2022-09-20T15:57:16.208Z] 	at com.microsoft.azure.functions.worker.binding.BindingDataStore.getTriggerMetatDataByName(BindingDataStore.java:66)
[2022-09-20T15:57:16.208Z] 	at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:62)
[2022-09-20T15:57:16.208Z] 	at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:42)
[2022-09-20T15:57:16.208Z] 	at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:53)
[2022-09-20T15:57:16.208Z] 	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:61)
[2022-09-20T15:57:16.208Z] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2022-09-20T15:57:16.208Z] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2022-09-20T15:57:16.208Z] 	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2022-09-20T15:57:16.208Z] 	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2022-09-20T15:57:16.208Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2022-09-20T15:57:16.209Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2022-09-20T15:57:16.209Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2022-09-20T15:57:16.209Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2022-09-20T15:57:16.209Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
[2022-09-20T15:57:16.209Z] .
````

BUT if I use another program without the function, I'm able to retreive the information that I need

````
 /**
     * Main method to demonstrate starting and stopping a {@link EventProcessorClient}.
     *
     * @param args The input arguments to this executable.
     * @throws Exception If there are any errors while running the {@link EventProcessorClient}.
     */
    public static void main(String[] args) throws Exception {

        Logger logger = LoggerFactory.getLogger(EventProcessorClientSample.class);
        Consumer<EventContext> processEvent = eventContext -> {
            logger.error(
                "Processing event: Event Hub name = {}; consumer group name = {}; partition id = {}; sequence number = {}; body {}",
                eventContext.getPartitionContext().getEventHubName(),
                eventContext.getPartitionContext().getConsumerGroup(),
                eventContext.getPartitionContext().getPartitionId(),
                eventContext.getEventData().getSequenceNumber(),
                eventContext.getEventData().getBodyAsString());

            eventContext.updateCheckpoint();
        };

        // This error handler logs the error that occurred and keeps the processor running. If the error occurred in
        // a specific partition and had to be closed, the ownership of the partition will be given up and will allow
        // other processors to claim ownership of the partition.
        Consumer<ErrorContext> processError = errorContext -> {
            logger.error("Error while processing {}, {}, {}, {}", errorContext.getPartitionContext().getEventHubName(),
                errorContext.getPartitionContext().getConsumerGroup(),
                errorContext.getPartitionContext().getPartitionId(),
                errorContext.getThrowable().getMessage());
        };

        EventProcessorClientBuilder eventProcessorClientBuilder = new EventProcessorClientBuilder()
            //.consumerGroup(EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME)
            .consumerGroup("test")
            .connectionString(EH_CONNECTION_STRING)
            .processEvent(processEvent)
            .processError(processError)
            .checkpointStore(new SampleCheckpointStore());

        EventProcessorClient eventProcessorClient = eventProcessorClientBuilder.buildEventProcessorClient();
        System.out.println("Starting event processor");
        eventProcessorClient.start();
        eventProcessorClient.start(); // should be a no-op
````

and the output is this
````
12:57:07.218 [partition-pump-2-2] ERROR c.a.m.e.EventProcessorClientSample - Processing event: Event Hub name = iot-to-eventhub-devices; consumer group name = test; partition id = 2; sequence number = 52; body {"version":33,"properties":{"desired":{"test":"1","coucu":"cdsdfdfvd1acbcde","$metadata":{"$lastUpdated":"2022-09-20T15:57:15.9068423Z","$lastUpdatedVersion":32,"test":{"$lastUpdated":"2022-09-20T15:57:15.9068423Z","$lastUpdatedVersion":32},"coucu":{"$lastUpdated":"2022-09-20T15:57:15.9068423Z","$lastUpdatedVersion":32}},"$version":32}}}

12:57:12.634 [partition-pump-2-2] ERROR c.a.m.e.EventProcessorClientSample - Processing event: Event Hub name = iot-to-eventhub-devices; consumer group name = test; partition id = 2; sequence number = 53; body [{"op":"replace","path":"/$metadata/test/desiredVersion","value":32},{"op":"replace","path":"/$metadata/coucu/desiredValue","value":"cdsdfdfvd1acbcde"},{"op":"replace","path":"/$metadata/coucu/desiredVersion","value":32}]

````

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/191879/191319019-11ac7102-b963-4390-bf84-3e5a3ebaa4ca.png">

**Comment by kaibocai** [comment]
Hi @survivant , thanks for opening the issue. Here is an example to get the meta data of event from EventHub, instead of using a Object array can you try the Map as showing in the example. https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=in-process%2Cfunctionsv2%2Cextensionv5&pivots=programming-language-java#example

Thanks.

**Comment by survivant** [comment]
@kaibocai thanks.  That code work fine.
